// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetMushroomsByMushroomIdData, GetMushroomsByMushroomIdResponses, GetMushroomsData, GetMushroomsResponses, GetRecipesData, GetRecipesResponses, PostMushroomsData, PostMushroomsErrors, PostMushroomsResponses, PostRecipesData, PostRecipesErrors, PostRecipesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * きのこ情報の一覧を取得する。
 */
export const getMushrooms = <ThrowOnError extends boolean = false>(options?: Options<GetMushroomsData, ThrowOnError>) => (options?.client ?? client).get<GetMushroomsResponses, unknown, ThrowOnError>({ url: '/mushrooms/', ...options });

/**
 * きのこを登録する。
 */
export const postMushrooms = <ThrowOnError extends boolean = false>(options: Options<PostMushroomsData, ThrowOnError>) => (options.client ?? client).post<PostMushroomsResponses, PostMushroomsErrors, ThrowOnError>({
    url: '/mushrooms/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * きのこの情報を取得する。
 */
export const getMushroomsByMushroomId = <ThrowOnError extends boolean = false>(options: Options<GetMushroomsByMushroomIdData, ThrowOnError>) => (options.client ?? client).get<GetMushroomsByMushroomIdResponses, unknown, ThrowOnError>({ url: '/mushrooms/{mushroom_id}/', ...options });

/**
 * 料理レシピの一覧を取得する。
 */
export const getRecipes = <ThrowOnError extends boolean = false>(options?: Options<GetRecipesData, ThrowOnError>) => (options?.client ?? client).get<GetRecipesResponses, unknown, ThrowOnError>({ url: '/recipes/', ...options });

/**
 * 料理レシピを登録する。
 */
export const postRecipes = <ThrowOnError extends boolean = false>(options: Options<PostRecipesData, ThrowOnError>) => (options.client ?? client).post<PostRecipesResponses, PostRecipesErrors, ThrowOnError>({
    url: '/recipes/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
