// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.example.com' | (string & {});
};

export type Http422UnprocessableEntity = {
    detail?: string;
    code?: string;
};

export type Http422InvalidRequestBody = {
    '*'?: Array<string>;
    code?: {
        '*'?: Array<string>;
    };
};

export type PaginationParts = {
    /**
     * 総数
     */
    count: number;
    /**
     * 次のページへのURL
     */
    next: string | null;
    /**
     * 前のページへのURL
     */
    previous: string | null;
};

export type Mushroom = {
    /**
     * きのこID
     */
    readonly id: string;
    /**
     * きのこ名
     */
    name: string;
    /**
     * きのこの概要
     */
    description: string;
    /**
     * 購入可能か
     */
    orderable: boolean;
    /**
     * 大きさの種類
     */
    size: 'small' | 'medium' | 'large';
    /**
     * おいしさスコア
     */
    tastiness?: number | null;
    /**
     * 状態
     */
    conditions?: {
        [key: string]: string | number;
    };
};

/**
 * きのこの部分更新で変更可能な項目
 */
export type MushroomUpdate = {
    /**
     * きのこ名
     */
    name?: string;
    /**
     * きのこの概要
     */
    description?: string;
    /**
     * 購入可能か
     */
    orderable?: boolean;
    /**
     * 大きさの種類
     */
    size?: 'small' | 'medium' | 'large';
    /**
     * おいしさスコア
     */
    tastiness?: number | null;
    /**
     * 状態
     */
    conditions?: {
        [key: string]: string | number;
    };
};

export type Recipe = {
    /**
     * レシピID
     */
    readonly id: string;
    /**
     * レシピ名
     */
    title: string;
    /**
     * 手順
     */
    instructions: string;
    /**
     * 使用するきのこ一覧
     */
    ingredients: Array<Mushroom>;
};

export type MushroomWritable = {
    /**
     * きのこ名
     */
    name: string;
    /**
     * きのこの概要
     */
    description: string;
    /**
     * 購入可能か
     */
    orderable: boolean;
    /**
     * 大きさの種類
     */
    size: 'small' | 'medium' | 'large';
    /**
     * おいしさスコア
     */
    tastiness?: number | null;
    /**
     * 状態
     */
    conditions?: {
        [key: string]: string | number;
    };
    /**
     * 登録時に既存データとの重複チェックを必須にするフラグ
     */
    duplicate_check: boolean;
};

/**
 * きのこの部分更新で変更可能な項目
 */
export type MushroomUpdateWritable = {
    /**
     * きのこ名
     */
    name?: string;
    /**
     * きのこの概要
     */
    description?: string;
    /**
     * 購入可能か
     */
    orderable?: boolean;
    /**
     * 大きさの種類
     */
    size?: 'small' | 'medium' | 'large';
    /**
     * おいしさスコア
     */
    tastiness?: number | null;
    /**
     * 状態
     */
    conditions?: {
        [key: string]: string | number;
    };
    /**
     * 登録時に既存データとの重複チェックを必須にするフラグ
     */
    duplicate_check?: boolean;
};

export type RecipeWritable = {
    /**
     * レシピ名
     */
    title: string;
    /**
     * 手順
     */
    instructions: string;
    /**
     * 使用するきのこ一覧
     */
    ingredients: Array<MushroomWritable>;
};

export type PaginationLimit = number;

export type PaginationOffset = number;

/**
 * きのこID
 */
export type MushroomId = string;

export type GetMushroomsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/mushrooms/';
};

export type GetMushroomsResponses = {
    /**
     * 正常終了
     */
    200: {
        results: Array<Mushroom>;
    } & PaginationParts;
};

export type GetMushroomsResponse = GetMushroomsResponses[keyof GetMushroomsResponses];

export type PostMushroomsData = {
    body: MushroomWritable;
    path?: never;
    query?: never;
    url: '/mushrooms/';
};

export type PostMushroomsErrors = {
    /**
     * 登録できない
     */
    422: Http422UnprocessableEntity | Http422InvalidRequestBody;
};

export type PostMushroomsError = PostMushroomsErrors[keyof PostMushroomsErrors];

export type PostMushroomsResponses = {
    /**
     * 正常に作成
     */
    201: Mushroom;
};

export type PostMushroomsResponse = PostMushroomsResponses[keyof PostMushroomsResponses];

export type GetMushroomsByMushroomIdData = {
    body?: never;
    path: {
        /**
         * きのこID
         */
        mushroom_id: string;
    };
    query?: never;
    url: '/mushrooms/{mushroom_id}/';
};

export type GetMushroomsByMushroomIdResponses = {
    /**
     * 正常に取得
     */
    200: {
        results: Array<Mushroom>;
    };
};

export type GetMushroomsByMushroomIdResponse = GetMushroomsByMushroomIdResponses[keyof GetMushroomsByMushroomIdResponses];

export type GetRecipesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/recipes/';
};

export type GetRecipesResponses = {
    /**
     * 正常終了
     */
    200: {
        results: Array<Recipe>;
    } & PaginationParts;
};

export type GetRecipesResponse = GetRecipesResponses[keyof GetRecipesResponses];

export type PostRecipesData = {
    body: RecipeWritable;
    path?: never;
    query?: never;
    url: '/recipes/';
};

export type PostRecipesErrors = {
    /**
     * 登録できない
     */
    422: Http422InvalidRequestBody;
};

export type PostRecipesError = PostRecipesErrors[keyof PostRecipesErrors];

export type PostRecipesResponses = {
    /**
     * 正常に作成
     */
    201: Recipe;
};

export type PostRecipesResponse = PostRecipesResponses[keyof PostRecipesResponses];
