// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { GetMushroomsData, GetMushroomsError, GetMushroomsResponse, PostMushroomsData, PostMushroomsError, PostMushroomsResponse, GetMushroomsByMushroomIdData, GetMushroomsByMushroomIdError, GetMushroomsByMushroomIdResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * きのこ情報の一覧を取得する。
 */
export const getMushrooms = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetMushroomsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMushroomsResponse, GetMushroomsError, ThrowOnError>({
        ...options,
        url: '/mushrooms/'
    });
};

/**
 * きのこを登録する。
 */
export const postMushrooms = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PostMushroomsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostMushroomsResponse, PostMushroomsError, ThrowOnError>({
        ...options,
        url: '/mushrooms/'
    });
};

/**
 * きのこの情報を取得する。
 */
export const getMushroomsByMushroomId = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetMushroomsByMushroomIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMushroomsByMushroomIdResponse, GetMushroomsByMushroomIdError, ThrowOnError>({
        ...options,
        url: '/mushrooms/{mushroom_id}/'
    });
};