// This file is auto-generated by @hey-api/openapi-ts

export type Http422InvalidRequestBody = {
    '*'?: Array<(string)>;
    code?: {
        '*'?: Array<(string)>;
    };
};

export type Http422UnprocessableEntity = {
    detail?: string;
    code?: string;
};

export type Mushroom = {
    /**
     * きのこID
     */
    readonly id: string;
    /**
     * きのこ名
     */
    name: string;
    /**
     * きのこの概要
     */
    description: string;
    /**
     * 購入可能か
     */
    orderable: boolean;
    /**
     * 大きさの種類
     */
    size: 'small' | 'medium' | 'large';
    /**
     * おいしさスコア
     */
    tastiness?: (number) | null;
    /**
     * 状態
     */
    conditions?: {
        [key: string]: (string | number);
    };
};

/**
 * 大きさの種類
 */
export type size = 'small' | 'medium' | 'large';

export type PaginationParts = {
    /**
     * 総数
     */
    count: number;
    /**
     * 次のページへのURL
     */
    next: (string) | null;
    /**
     * 前のページへのURL
     */
    previous: (string) | null;
};

/**
 * きのこID
 */
export type ParameterMushroomID = string;

export type ParameterPaginationLimit = number;

export type ParameterPaginationOffset = number;

export type GetMushroomsData = {
    query?: {
        limit?: number;
        offset?: number;
    };
};

export type GetMushroomsResponse = (({
    results: Array<Mushroom>;
} & PaginationParts));

export type GetMushroomsError = unknown;

export type PostMushroomsData = {
    body: Mushroom;
};

export type PostMushroomsResponse = (Mushroom);

export type PostMushroomsError = ((Http422UnprocessableEntity | Http422InvalidRequestBody));

export type GetMushroomsByMushroomIdData = {
    path: {
        /**
         * きのこID
         */
        mushroom_id: string;
    };
};

export type GetMushroomsByMushroomIdResponse = (({
    results: Array<Mushroom>;
}));

export type GetMushroomsByMushroomIdError = unknown;