/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Mushroom } from './Mushroom';
import {
    MushroomFromJSON,
    MushroomFromJSONTyped,
    MushroomToJSON,
    MushroomToJSONTyped,
} from './Mushroom';

/**
 * 
 * @export
 * @interface MushroomsMushroomIdGet200Response
 */
export interface MushroomsMushroomIdGet200Response {
    /**
     * 
     * @type {Array<Mushroom>}
     * @memberof MushroomsMushroomIdGet200Response
     */
    results: Array<Mushroom>;
}

/**
 * Check if a given object implements the MushroomsMushroomIdGet200Response interface.
 */
export function instanceOfMushroomsMushroomIdGet200Response(value: object): value is MushroomsMushroomIdGet200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function MushroomsMushroomIdGet200ResponseFromJSON(json: any): MushroomsMushroomIdGet200Response {
    return MushroomsMushroomIdGet200ResponseFromJSONTyped(json, false);
}

export function MushroomsMushroomIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MushroomsMushroomIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(MushroomFromJSON)),
    };
}

export function MushroomsMushroomIdGet200ResponseToJSON(json: any): MushroomsMushroomIdGet200Response {
    return MushroomsMushroomIdGet200ResponseToJSONTyped(json, false);
}

export function MushroomsMushroomIdGet200ResponseToJSONTyped(value?: MushroomsMushroomIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(MushroomToJSON)),
    };
}

