/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationParts
 */
export interface PaginationParts {
    /**
     * 総数
     * @type {number}
     * @memberof PaginationParts
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof PaginationParts
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof PaginationParts
     */
    previous: string | null;
}

/**
 * Check if a given object implements the PaginationParts interface.
 */
export function instanceOfPaginationParts(value: object): value is PaginationParts {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    return true;
}

export function PaginationPartsFromJSON(json: any): PaginationParts {
    return PaginationPartsFromJSONTyped(json, false);
}

export function PaginationPartsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationParts {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
    };
}

export function PaginationPartsToJSON(json: any): PaginationParts {
    return PaginationPartsToJSONTyped(json, false);
}

export function PaginationPartsToJSONTyped(value?: PaginationParts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
    };
}

