/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Http422UnprocessableEntity
 */
export interface Http422UnprocessableEntity {
    /**
     * 
     * @type {string}
     * @memberof Http422UnprocessableEntity
     */
    detail?: string;
    /**
     * 
     * @type {string}
     * @memberof Http422UnprocessableEntity
     */
    code?: string;
}

/**
 * Check if a given object implements the Http422UnprocessableEntity interface.
 */
export function instanceOfHttp422UnprocessableEntity(value: object): value is Http422UnprocessableEntity {
    return true;
}

export function Http422UnprocessableEntityFromJSON(json: any): Http422UnprocessableEntity {
    return Http422UnprocessableEntityFromJSONTyped(json, false);
}

export function Http422UnprocessableEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Http422UnprocessableEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : json['detail'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function Http422UnprocessableEntityToJSON(json: any): Http422UnprocessableEntity {
    return Http422UnprocessableEntityToJSONTyped(json, false);
}

export function Http422UnprocessableEntityToJSONTyped(value?: Http422UnprocessableEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
        'code': value['code'],
    };
}

