/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Http422InvalidRequestBodyCode
 */
export interface Http422InvalidRequestBodyCode {
    /**
     * 
     * @type {Array<string>}
     * @memberof Http422InvalidRequestBodyCode
     */
    ?: Array<string>;
}

/**
 * Check if a given object implements the Http422InvalidRequestBodyCode interface.
 */
export function instanceOfHttp422InvalidRequestBodyCode(value: object): value is Http422InvalidRequestBodyCode {
    return true;
}

export function Http422InvalidRequestBodyCodeFromJSON(json: any): Http422InvalidRequestBodyCode {
    return Http422InvalidRequestBodyCodeFromJSONTyped(json, false);
}

export function Http422InvalidRequestBodyCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Http422InvalidRequestBodyCode {
    if (json == null) {
        return json;
    }
    return {
        
        '': json['*'] == null ? undefined : json['*'],
    };
}

export function Http422InvalidRequestBodyCodeToJSON(json: any): Http422InvalidRequestBodyCode {
    return Http422InvalidRequestBodyCodeToJSONTyped(json, false);
}

export function Http422InvalidRequestBodyCodeToJSONTyped(value?: Http422InvalidRequestBodyCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '*': value[''],
    };
}

