/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type MushroomConditionsValue
 * 
 * @export
 */
export type MushroomConditionsValue = number | string;

export function MushroomConditionsValueFromJSON(json: any): MushroomConditionsValue {
    return MushroomConditionsValueFromJSONTyped(json, false);
}

export function MushroomConditionsValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): MushroomConditionsValue {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function MushroomConditionsValueToJSON(json: any): any {
    return MushroomConditionsValueToJSONTyped(json, false);
}

export function MushroomConditionsValueToJSONTyped(value?: MushroomConditionsValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

