/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MushroomConditionsValue } from './MushroomConditionsValue';
import {
    MushroomConditionsValueFromJSON,
    MushroomConditionsValueFromJSONTyped,
    MushroomConditionsValueToJSON,
    MushroomConditionsValueToJSONTyped,
} from './MushroomConditionsValue';

/**
 * きのこの部分更新で変更可能な項目
 * @export
 * @interface MushroomUpdate
 */
export interface MushroomUpdate {
    /**
     * きのこ名
     * @type {string}
     * @memberof MushroomUpdate
     */
    name?: string;
    /**
     * きのこの概要
     * @type {string}
     * @memberof MushroomUpdate
     */
    description?: string;
    /**
     * 購入可能か
     * @type {boolean}
     * @memberof MushroomUpdate
     */
    orderable?: boolean;
    /**
     * 大きさの種類
     * @type {string}
     * @memberof MushroomUpdate
     */
    size?: MushroomUpdateSizeEnum;
    /**
     * おいしさスコア
     * @type {number}
     * @memberof MushroomUpdate
     */
    tastiness?: number | null;
    /**
     * 状態
     * @type {{ [key: string]: MushroomConditionsValue; }}
     * @memberof MushroomUpdate
     */
    conditions?: { [key: string]: MushroomConditionsValue; };
    /**
     * 登録時に既存データとの重複チェックを必須にするフラグ
     * @type {boolean}
     * @memberof MushroomUpdate
     */
    duplicateCheck?: boolean;
}


/**
 * @export
 */
export const MushroomUpdateSizeEnum = {
    Small: 'small',
    Medium: 'medium',
    Large: 'large'
} as const;
export type MushroomUpdateSizeEnum = typeof MushroomUpdateSizeEnum[keyof typeof MushroomUpdateSizeEnum];


/**
 * Check if a given object implements the MushroomUpdate interface.
 */
export function instanceOfMushroomUpdate(value: object): value is MushroomUpdate {
    return true;
}

export function MushroomUpdateFromJSON(json: any): MushroomUpdate {
    return MushroomUpdateFromJSONTyped(json, false);
}

export function MushroomUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MushroomUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'orderable': json['orderable'] == null ? undefined : json['orderable'],
        'size': json['size'] == null ? undefined : json['size'],
        'tastiness': json['tastiness'] == null ? undefined : json['tastiness'],
        'conditions': json['conditions'] == null ? undefined : (mapValues(json['conditions'], MushroomConditionsValueFromJSON)),
        'duplicateCheck': json['duplicate_check'] == null ? undefined : json['duplicate_check'],
    };
}

export function MushroomUpdateToJSON(json: any): MushroomUpdate {
    return MushroomUpdateToJSONTyped(json, false);
}

export function MushroomUpdateToJSONTyped(value?: MushroomUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'orderable': value['orderable'],
        'size': value['size'],
        'tastiness': value['tastiness'],
        'conditions': value['conditions'] == null ? undefined : (mapValues(value['conditions'], MushroomConditionsValueToJSON)),
        'duplicate_check': value['duplicateCheck'],
    };
}

