/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Http422InvalidRequestBody } from './Http422InvalidRequestBody';
import {
    instanceOfHttp422InvalidRequestBody,
    Http422InvalidRequestBodyFromJSON,
    Http422InvalidRequestBodyFromJSONTyped,
    Http422InvalidRequestBodyToJSON,
} from './Http422InvalidRequestBody';
import type { Http422UnprocessableEntity } from './Http422UnprocessableEntity';
import {
    instanceOfHttp422UnprocessableEntity,
    Http422UnprocessableEntityFromJSON,
    Http422UnprocessableEntityFromJSONTyped,
    Http422UnprocessableEntityToJSON,
} from './Http422UnprocessableEntity';

/**
 * @type MushroomsPost422Response
 * 
 * @export
 */
export type MushroomsPost422Response = Http422InvalidRequestBody | Http422UnprocessableEntity;

export function MushroomsPost422ResponseFromJSON(json: any): MushroomsPost422Response {
    return MushroomsPost422ResponseFromJSONTyped(json, false);
}

export function MushroomsPost422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MushroomsPost422Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfHttp422InvalidRequestBody(json)) {
        return Http422InvalidRequestBodyFromJSONTyped(json, true);
    }
    if (instanceOfHttp422UnprocessableEntity(json)) {
        return Http422UnprocessableEntityFromJSONTyped(json, true);
    }
    return {} as any;
}

export function MushroomsPost422ResponseToJSON(json: any): any {
    return MushroomsPost422ResponseToJSONTyped(json, false);
}

export function MushroomsPost422ResponseToJSONTyped(value?: MushroomsPost422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfHttp422InvalidRequestBody(value)) {
        return Http422InvalidRequestBodyToJSON(value as Http422InvalidRequestBody);
    }
    if (instanceOfHttp422UnprocessableEntity(value)) {
        return Http422UnprocessableEntityToJSON(value as Http422UnprocessableEntity);
    }
    return {};
}

