/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Mushroom } from './Mushroom';
import {
    MushroomFromJSON,
    MushroomFromJSONTyped,
    MushroomToJSON,
    MushroomToJSONTyped,
} from './Mushroom';

/**
 * 
 * @export
 * @interface MushroomsGet200Response
 */
export interface MushroomsGet200Response {
    /**
     * 総数
     * @type {number}
     * @memberof MushroomsGet200Response
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof MushroomsGet200Response
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof MushroomsGet200Response
     */
    previous: string | null;
    /**
     * 
     * @type {Array<Mushroom>}
     * @memberof MushroomsGet200Response
     */
    results: Array<Mushroom>;
}

/**
 * Check if a given object implements the MushroomsGet200Response interface.
 */
export function instanceOfMushroomsGet200Response(value: object): value is MushroomsGet200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function MushroomsGet200ResponseFromJSON(json: any): MushroomsGet200Response {
    return MushroomsGet200ResponseFromJSONTyped(json, false);
}

export function MushroomsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MushroomsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': ((json['results'] as Array<any>).map(MushroomFromJSON)),
    };
}

export function MushroomsGet200ResponseToJSON(json: any): MushroomsGet200Response {
    return MushroomsGet200ResponseToJSONTyped(json, false);
}

export function MushroomsGet200ResponseToJSONTyped(value?: MushroomsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(MushroomToJSON)),
    };
}

