/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Recipe } from './Recipe';
import {
    RecipeFromJSON,
    RecipeFromJSONTyped,
    RecipeToJSON,
    RecipeToJSONTyped,
} from './Recipe';

/**
 * 
 * @export
 * @interface RecipesGet200Response
 */
export interface RecipesGet200Response {
    /**
     * 総数
     * @type {number}
     * @memberof RecipesGet200Response
     */
    count: number;
    /**
     * 次のページへのURL
     * @type {string}
     * @memberof RecipesGet200Response
     */
    next: string | null;
    /**
     * 前のページへのURL
     * @type {string}
     * @memberof RecipesGet200Response
     */
    previous: string | null;
    /**
     * 
     * @type {Array<Recipe>}
     * @memberof RecipesGet200Response
     */
    results: Array<Recipe>;
}

/**
 * Check if a given object implements the RecipesGet200Response interface.
 */
export function instanceOfRecipesGet200Response(value: object): value is RecipesGet200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function RecipesGet200ResponseFromJSON(json: any): RecipesGet200Response {
    return RecipesGet200ResponseFromJSONTyped(json, false);
}

export function RecipesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': ((json['results'] as Array<any>).map(RecipeFromJSON)),
    };
}

export function RecipesGet200ResponseToJSON(json: any): RecipesGet200Response {
    return RecipesGet200ResponseToJSONTyped(json, false);
}

export function RecipesGet200ResponseToJSONTyped(value?: RecipesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RecipeToJSON)),
    };
}

