/* tslint:disable */
/* eslint-disable */
/**
 * 検証用 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Mushroom } from './Mushroom';
import {
    MushroomFromJSON,
    MushroomFromJSONTyped,
    MushroomToJSON,
    MushroomToJSONTyped,
} from './Mushroom';

/**
 * 
 * @export
 * @interface Recipe
 */
export interface Recipe {
    /**
     * レシピID
     * @type {string}
     * @memberof Recipe
     */
    readonly id: string;
    /**
     * レシピ名
     * @type {string}
     * @memberof Recipe
     */
    title: string;
    /**
     * 手順
     * @type {string}
     * @memberof Recipe
     */
    instructions: string;
    /**
     * 使用するきのこ一覧
     * @type {Array<Mushroom>}
     * @memberof Recipe
     */
    ingredients: Array<Mushroom>;
}

/**
 * Check if a given object implements the Recipe interface.
 */
export function instanceOfRecipe(value: object): value is Recipe {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    return true;
}

export function RecipeFromJSON(json: any): Recipe {
    return RecipeFromJSONTyped(json, false);
}

export function RecipeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recipe {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'instructions': json['instructions'],
        'ingredients': ((json['ingredients'] as Array<any>).map(MushroomFromJSON)),
    };
}

export function RecipeToJSON(json: any): Recipe {
    return RecipeToJSONTyped(json, false);
}

export function RecipeToJSONTyped(value?: Omit<Recipe, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'instructions': value['instructions'],
        'ingredients': ((value['ingredients'] as Array<any>).map(MushroomToJSON)),
    };
}

